# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_put_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='put_time',
            new_name='pub_time',
        ),
    ]
